from .base import *

CORS_ORIGIN_ALLOW_ALL = True
DEBUG = True

EMAIL_HOST = "127.0.0.1"
EMAIL_HOST_PASSWORD = ""
EMAIL_HOST_USER = ""
EMAIL_PORT = 1025
EMAIL_USE_TLS = False

STATIC_URL = "/static/"
